version: '3.9'
services:
    python:
        build: .
        command: python3 src_db/mongo_script.py
        links: 
         - mongo
    mongo:
        image: mongo:4.4
        ports:
         - "27017:27017/tcp"


