version: "3.9"
services:
    python:
        build: .
        command: python3 src_db/mongo_script.py 
        ports:         
         - "80:80/tcp"
        links: 
         - mongo
    mongo:
        image: 
         - mongo:4.4
        ports:
         - "127.0.0.1.27017:27017/tcp"


